### ISSUE TITLE
lazy loaded components

### ISSUE THREAD

**Issue by joshua1** [lyohaplotinka/easyroute#11]
Hi @lyohaplotinka using svelte-easyroute as an example, how is lazy loading of components handled. Given that there is no documentation of any feature. one of the source files mentioned code splitting feature of Webpack. does lazy loading rely solely on that ?

**Comment by lyohaplotinka** [comment]
Hi @joshua1! 

Documentation is on the way, sorry for writing it for so long.
Yes, lazy loading is designed primarily to be used with Webpack or Rollup. However, the main condition for lazy loading is that the component you pass into the routes array must be a function that returns a promise. As a result of resolving this promise, the component itself should be returned.

In theory, you could write this code yourself, but the builders do it for you.

**Comment by joshua1** [comment]
Thanks @lyohaplotinka
