### ISSUE TITLE
Trim trailing slash

### ISSUE THREAD

**Issue by arda-** [lyohaplotinka/easyroute#12]
I'd like to be able to categorically omit the trailing slash (eg `foo.bar/baz` instead of `foo.bar/baz/`).

I looked under the hood, and there's a util for this :https://github.com/easyroute-router/easyroute-core/blob/707a263c1e670b0d8a58d5259813c9d845b4718b/lib/src/utils/path/deleteLastSlash.ts#L1

And we could implement optional the trailing slash trim during URL construction here:
https://github.com/easyroute-router/easyroute-core/blob/707a263c1e670b0d8a58d5259813c9d845b4718b/lib/src/utils/path/constructUrl.ts#L1-L7

Perhaps we could expose that as an option on the RouterSettings?

https://github.com/easyroute-router/easyroute-core/blob/707a263c1e670b0d8a58d5259813c9d845b4718b/types.d.ts#L52-L56

**Comment by lyohaplotinka** [comment]
Hello @arda-! 
Good idea, I will add it in next minor release

**Comment by lyohaplotinka** [comment]
@arda-, added in v1.3.4-1

**Comment by arda-** [comment]
amazing, thank you! :)
